- nginx/promotions.conf
> Refer to correct SSL certificate

- conf/deploy.json
A bit scary having it inferred by the package name.
> Add explicit apps name to Riff Raff config

- app/controllers/RatePlanController.scala
- app/views/main.scala.html
- app/wiring/AppComponents.scala
- app/wiring/AppLoader.scala
- app/wiring/MultiRouter.scala
- conf/routes
- frontend/src/controllers/EditPromotionController.es6
- frontend/src/controllers/StageController.es6
- frontend/src/directives/MdlUpgrade.es6
- frontend/src/directives/StageMenu.es6
- frontend/src/main.es6
- frontend/src/services/RatePlanService.es6
- frontend/src/templates/Form.html
- frontend/src/templates/Promotions.html
- frontend/src/templates/StageMenu.html
> Beginnings of edit form

- app/controllers/PromotionController.scala
- conf/routes
- frontend/src/controllers/PromotionTypeController.es6
- frontend/src/directives/DeleteEmpty.es6
- frontend/src/directives/Modal.es6
- frontend/src/directives/PromotionType.es6
- frontend/src/main.es6
- frontend/src/services/PromotionService.es6
- frontend/src/templates/PromotionForm.html
- frontend/src/templates/PromotionType.html
> Promotion type field

- frontend/src/controllers/RatePlanListController.es6
- frontend/src/directives/PromotionType.es6
- frontend/src/directives/RatePlanList.es6
- frontend/src/main.es6
- frontend/src/templates/PromotionDates.html
- frontend/src/templates/PromotionForm.html
- frontend/src/templates/PromotionType.html
- frontend/src/templates/RatePlanList.html
> Move rate plans to its own directive

- app/views/main.scala.html
- frontend/sass/main.sass
- frontend/src/controllers/ChannelCodesController.es6
- frontend/src/directives/ChannelCodes.es6
- frontend/src/templates/CampaignForm.html
- frontend/src/templates/CampaignList.html
- frontend/src/templates/ChannelCodes.html
- frontend/src/templates/PromotionForm.html
- frontend/src/templates/PromotionList.html
- frontend/src/templates/StageMenu.html
Switch most of the app to angular-material over material design lite
> Channel codes tabs

- app/views/index.scala.html
- frontend/package.json
- frontend/sass/main.sass
- frontend/src/controllers/CampaignListController.es6
- frontend/src/controllers/EditCampaignController.es6
- frontend/src/controllers/PromotionFormController.es6
- frontend/src/controllers/PromotionListController.es6
- frontend/src/main.es6
- frontend/src/templates/CampaignForm.html
- frontend/src/templates/CampaignList.html
- frontend/src/templates/LandingPage.html
- frontend/src/templates/PromotionForm.html
- frontend/src/templates/PromotionList.html
> Add promotions

- app/views/main.scala.html
- frontend/sass/main.sass
- frontend/src/controllers/ChannelCodesController.es6
- frontend/src/controllers/EditCampaignController.es6
- frontend/src/controllers/PromotionFormController.es6
- frontend/src/controllers/PromotionListController.es6
- frontend/src/services/EnvironmentService.es6
- frontend/src/templates/CampaignForm.html
- frontend/src/templates/CampaignList.html
- frontend/src/templates/ChannelCodes.html
- frontend/src/templates/PromotionForm.html
- frontend/src/templates/PromotionList.html
- Auto-generated codes
- Display campaign name
- Display preview URL
- Tweaked field ordering
- Icon hyperlinks for (existing) promo code landing pages.
> Listing displayed field tweaks

- app/controllers/CountryController.scala
> Make UK mainland/overseas separate country groups

- frontend/sass/main.sass
- frontend/src/templates/PromotionList.html
> Fixed the overflow of the promo code list items

- frontend/Webpack.js
- frontend/package.json
> Call WebPack with optimize flags

- frontend/src/controllers/PromotionFormController.es6
- frontend/src/services/EnvironmentService.es6
- Correct landing page URL for the chosen environment.
cc @nlindblad @tomverran
> Correct landing page URL

- app/controllers/RatePlanController.scala
- frontend/sass/main.sass
- frontend/src/templates/LandingPage.html
- frontend/src/templates/PromotionForm.html
- frontend/src/templates/RatePlanList.html
- Ordered the rate plans in a logical way
- Layout tweaks to section colour selector, preview and save buttons
- Tweaked toolbar colour for subs
> Ordered the rate plans in a logical way

- cloudformation/memsub-promotions-cf.json
Needs to be tested, but it passes validation.
> Give cross account DynamoDB access to views

- app/controllers/PromotionController.scala
- frontend/sass/main.sass
- frontend/src/controllers/ChannelCodesController.es6
- frontend/src/controllers/PreviewPromotionController.es6
- frontend/src/controllers/PromotionFormController.es6
- frontend/src/directives/PreviewPromotion.es6
- frontend/src/main.es6
- frontend/src/services/PromotionService.es6
- frontend/src/templates/ChannelCodes.html
- frontend/src/templates/LandingPage.html
- frontend/src/templates/PromotionDates.html
- frontend/src/templates/PromotionForm.html
- frontend/src/templates/PromotionType.html
We also display an error message if the server validation fails
> Shore up clientside form validation

- frontend/sass/main.sass
- frontend/src/templates/CampaignList.html
- frontend/src/templates/PromotionList.html
Highlight the selected campaign.
Add space between groups of promo codes.
cc @tomverran
> Highlight the selected campaign

- conf/logger.conf
Updating to use its own Cloudwatch Log Group, rather than Membership Frontend's
cc @nlindblad @tomverran
> Updating to use its own Cloudwatch Log Group

- app/controllers/CampaignController.scala
- app/controllers/PromotionController.scala
> A few small ordering tweaks to make the promo code tool easier to use

- app/actions/GoogleAuthAction.scala
- Give all members of the Acquisition team access to the promotions tool
cc @tomverran
> Give all members of the Acquisition team access to the promotions tool

- cloudformation/memsub-promotions-cf.json
This lets us deploy the UAT lambda via RiffRaff (RiffRaff calls this stage 'TEST')
cc @tomverran @johnduffell @pvighi
> Rename lambda to align to riffraff names.

- app/conf/WeeklyPlans.scala
- app/controllers/RatePlanController.scala
- app/wiring/AppComponents.scala
- conf/application.conf
Add weekly rate plans to the promotions tool.
> Add weekly rate plans

- app/conf/CatalogService.scala
- app/controllers/RatePlanController.scala
- app/wiring/AppComponents.scala
- build.sbt
- conf/touchpoint.conf
- frontend/sass/main.sass
- frontend/src/controllers/RatePlanListController.es6
- frontend/src/directives/RatePlanList.es6
- frontend/src/templates/PromotionForm.html
- frontend/src/templates/RatePlanList.html
this brings the catalog into the promo tool and performs gbp price lookups
ui work ongoing
conf file update required
> enhance rateplans with price

- app/conf/WeeklyPlans.scala
- app/controllers/RatePlanController.scala
- build.sbt
- conf/application.conf
- Added new Rate Plan IDs to the config and the WeeklySchedules case class.
cc @paulbrown1982
> add one year and zone c

- frontend/src/controllers/MultiPromotionTypeController.es6
- frontend/src/controllers/PromotionTypeController.es6
- frontend/src/directives/PromotionType.es6
- frontend/src/directives/RatePlanList.es6
- frontend/src/templates/MultiPromotionType.html
- frontend/src/templates/PromotionForm.html
- frontend/src/templates/PromotionType.html
Allow multiple benefits on one promotion and fix the logic for it.
> Multi promotion

- frontend/package.json
- frontend/src/controllers/RatePlanListController.es6
I really messed up the discount calculator. 
Here's something more robust.
@paulbrown1982 
@jacobwinch
> Fix discount calculation

- frontend/src/controllers/PreviewPromotionController.es6
- frontend/src/templates/PromotionForm.html
Allow all promotions to be previewed, and don't waste the space if they can't. 
@paulbrown1982
> Promo preview

- build.sbt
https://github.com/guardian/membership-common/pull/419
> use membership common that understands frontend ids

- app/conf/WeeklyPlans.scala
- app/controllers/RatePlanController.scala
- build.sbt
- conf/application.conf
- frontend/src/templates/LandingPage.html
Allows six for six promotions and their landing pages.
> Six for six landing page.

- build.sbt
- frontend/src/controllers/PromotionTypeController.es6
- frontend/src/templates/PromotionType.html
https://github.com/guardian/membership-common/pull/448
> Renewal promotions

- build.sbt
forgot to push my final commit before merging. :( 
@jacobwinch
> dont use snapshot

- app/conf/PaperPlans.scala
- app/controllers/RatePlanController.scala
- conf/application.conf
Added a Sunday only package. 
Simply a clone of the Sunday+ with the Digital Pack charge, and the tax removed.
Also added the missing rate plans in Dev.
cc @jacobwinch @AWare
> Added a Sunday only package.

- cloudformation/memsub-promotions-cf.yaml
- lambdas/package.json
- lambdas/riff-raff.yaml
- lambdas/src/MembershipSub-PromoCode-View-Dynamo-to-Data-Lake.js
Added a second lambda to copy the PromoCode-View table over to the Data Lake.
cc @AWare
> Add datalake copy lambda

- README.md
- app/conf/PaperPlans.scala
- app/controllers/RatePlanController.scala
- conf/application.conf
- frontend/scss/main.scss
- frontend/src/templates/EnvironmentMenu.html
We are adding a new Saturday only subscription product so the promo tool needs to be able to include this product in promotions. This PR makes that possible.
> Saturday only product

- conf/riff-raff.yaml
> Try using an encrypted AMI

- build.sbt
> Use newer jackson-databind

- build.sbt
> Use the latest membership-common

- build.sbt
Version bump of `"com.gu" %% "play-googleauth"` to address Snyk issues.
> bump play-googleauth

- app/conf/WeeklyPlans.scala
- app/controllers/RatePlanController.scala
- conf/application.conf
Before screenshot:
After screenshot:
cc @rupertbates
> Add the one-year GW plans to the promo tool so we can discount 1-year renewals

- build.sbt
Updating jackson dependency due to Snky report:
https://app.snyk.io/org/the-guardian-cuu/project/d0c4fcd7-5943-49b1-878b-c7a8e9d64236/
cc @rupertbates @jfsoul
> Updating jackson dependency due to Snky report

- cloudformation/memsub-promotions-lambdas-cf.yaml
Also ensure Lambda Environment variables are maintained between cloudformings.
> Update node version of Lambdas as AWS no longer supports 6.10

- frontend/src/templates/LandingPage.html
- frontend/src/templates/PromotionForm.html
> Tiny copy changes

- frontend/src/templates/RatePlanList.html
Just noticed that the layout in Paper is a bit broken after #170 this fixes it
> One last layout tweak

- README.md
- lambdas/README.md
Now the lambda is CI/CD so I have updated the readmes accordingly
> Improve README and make it in a better location for the lambdas.

- README.md
This just makes the readme easier to read.
> rejig readme

- build.sbt
- cloudformation/memsub-promotions-cf.yaml
- conf/riff-raff.yaml
- frontend/yarn.lock
similar to https://github.com/guardian/membership-frontend/pull/1990 and https://github.com/guardian/subscriptions-frontend/pull/1324
preview CFN works ok in CODE (stack is up to date already)
deployed and working in CODE.
> update promo tool to use supported ubuntu and ARM

- cloudformation/memsub-promotions-cf.yaml
Add wazuh access
Similar to https://github.com/guardian/support-frontend/pull/2971
@jorgeazevedo 
TODO Test in CODE and check it's getting through okay
> add changes to allow wazuh access

- app/conf/WeeklyPlans.scala
- app/controllers/RatePlanController.scala
- build.sbt
- conf/application.conf
- project/build.properties
- sbt
co-authored-with: @rupertbates in the mobbing session
This PR adds a new tickbox to the rate plans section for guardian weekly, to cover the new monthly plan.
Tested locally against support CODE (dev zuora backend),  The discount appears and disappears on the checkout/landing page when you tick/untick.
> add monthly tickbox to the guardian weekly promo editing page

- .gitignore
- app/com/gu/memsub/auth/common/MemSub.scala
- app/controllers/AuthController.scala
- app/utils/CampaignUtils.scala
- app/wiring/AppComponents.scala
- build.sbt
- cloudformation/memsub-promotions-cf.yaml
- conf/DEV.conf
- conf/PROD.conf
- conf/application.conf
- project/build.properties
- project/plugins.sbt
> Update sbt + Play

- app/controllers/RatePlanController.scala
> Support Saturday rate plans

- project/plugins.sbt
for a vulnerability in filters-helpers
https://security.snyk.io/vuln/SNYK-JAVA-COMTYPESAFEPLAY-2855274
Tested in CODE
> Play 2.8.16

- conf/riff-raff.yaml
- project/plugins.sbt
something odd is happening with the rate plans in the UI, reverting this for now
Reverts guardian/memsub-promotions#248
> Revert "Ubuntu Jammy"

- README.md
for some reason if you're not in the google group it doesn't display an error, it just gives a redirect loop.  Probably a config issue.  This should help stop people being as confused until someone fixes the issue.
> readme improvement

- lambdas/package.json
- lambdas/yarn.lock
To patch critical vulnerability https://github.com/guardian/memsub-promotions/security/dependabot/162
> Update Babel 

- app/com/gu/memsub/subsv2/Plan.scala
- app/com/gu/memsub/subsv2/services/CatalogService.scala
> fix: use correct frontendIds for TierThree

- cloudformation/memsub-promotions-cf.yaml
this is not required and we should only be using SSM for access to instances
> Remove ssh port ingress

- app/com/gu/config/TierThreeRatePlanIds.scala
- app/com/gu/memsub/subsv2/Plan.scala
- app/com/gu/memsub/subsv2/services/CatalogService.scala
- app/controllers/RatePlanController.scala
- conf/touchpoint.CODE.conf
- conf/touchpoint.PROD.conf
We are adding four new rate plans into the Tier Three product to represent the archive being added as a benefit, these are V2 versions of the existing rate plans. 
This PR makes these rate plans available for discounting through the promo code tool
> Add in new V2 (archive) Tier Three rate plans

- cloudformation/memsub-promotions-cf.yaml
Make the promo code tool use IMDSv2 as part of FSBP compliance.
See [this doc](https://docs.google.com/document/d/1Q_ts5mbRvASCGo3UfsPHwUVvSXc3f2fkK2Fwp6N9Pxc/edit?tab=t.0) for more information
> Make promo code tool use IMDSv2

- app/com/gu/memsub/Price.scala
- app/com/gu/memsub/services/JsonDynamoService.scala
- app/com/gu/memsub/subsv2/Subscription.scala
- app/com/gu/memsub/subsv2/services/CatalogService.scala
- app/controllers/PromotionController.scala
- build.sbt
- frontend/src/main.es6
- frontend/src/templates/CampaignList.html
Fixing bug caused by earlier Angular upgrade where new campaigns can't be created.
Fixing several CVEs and deprecation notices reported in IntelliJ.
Fix Apache Commons vulnerability mentioned by the above and by [Dependabot](https://github.com/guardian/memsub-promotions/security/dependabot/186):
Deploy
> Fixing bug where Campaigns can't be created plus several CVEs and deprecation notices reported in IntelliJ

- build.sbt
Fixes Dependabot issue https://github.com/guardian/memsub-promotions/security/dependabot/197 about CVE-2025-48734 for commons-beanutils
> Fixing Dependabot issue about CVE-2025-48734 for commons-beanutils

- build.sbt
- project/plugins.sbt
> Update play to 3.0.7
