guardian/memsub-promotions

- frontend/src/directives/PromotionType.es6
- frontend/src/templates/PromotionForm.html
- frontend/src/templates/PromotionType.html
Put a message in the Promotion Type section (when on Membership view) which explains how the Rate plans are only used to determine the landing page tier, and won't affect the tracking promotion's eligibility.
> Tweak of messaging for tracking promotions

- frontend/src/templates/CampaignList.html
My last change [wrongly or rightly] made it so the JSON determines the ordering of the campaigns. So I've removed the template sorting override rather than applying the same name-based sort again. 
> Removing override of order-by

- frontend/src/services/PromotionService.es6
The UI treats it as a back-end validation error, but we can think about changing that if we add more client side validation in the future.
> Disallow same type of promo twice

- frontend/src/controllers/ChannelCodesController.es6
- frontend/src/controllers/EditCampaignController.es6
- frontend/src/controllers/PromotionFormController.es6
- frontend/src/templates/ChannelCodes.html
- frontend/src/templates/PromotionForm.html
Changes to the promo tool to support voucher launch activities:
- New Campaign displays in listing after creating it.
- Link next to promo code to checkout page for voucher, rather than only digipack.
- Save button sits alongside Save & Close in order to wait the 15 seconds for the promo to make it onto prod.
- Hide the landing page option for non-Digipack promos to save having to always untick it each time.
cc @pvighi @AWare
> Promo tool support for voucher launch activities

- build.sbt
- frontend/src/controllers/PromotionFormController.es6
- frontend/src/templates/ChannelCodes.html
- frontend/src/templates/LandingPage.html
- frontend/src/templates/PromotionForm.html
- frontend/src/templates/PromotionList.html
- frontend/src/templates/PromotionType.html
- Added new "Long terms and conditions" field to Incentive promotions.
- Added the channel name prefix to the list of codes under a promotion. See pic below.
- Updated promo code link to go to /terms page as that will always show, even if the promotion has expired or is not yet active.
- Ensured we use the new 'type' field for setting up the landing page angular model, deprecating the old 'productFamily'.
- Let the lading page area show either Voucher or Home Delivery for newspaper promotions
cc @AWare @johnduffell @pvighi @jacobwinch
> Promo tool updates for voucher promo launch

- app/controllers/PromotionController.scala
- Ensured that the timezone saved in dynamo for a promotion's start and end date time most likely matches that of the user using the promo code tool.
- Forced that the promotion start datetime is at the beginning of the day and that that the promotion end datetime is at the end of the day, thus making the dates on screen be 'inclusive'.
https://trello.com/c/k7Tcb6B5/88-fix-times-for-dates-shown-in-promo-tool
cc @AWare @JuliaBellis
> Make start date and end date for promotions be at the beginning and end of the respective days

- app/controllers/PromotionController.scala
I've decided that we should sort the promotions within a campaign by name not by their latest start date. This lets people manage series of promotions (like Guardian Weekly renewals) better.
cc @AWare
> Sort the promotions within a campaign by name not by their latest start date

- frontend/src/services/PromotionService.es6
Added a function at the service layer to sort the channel names and promo codes lexicographically, to make the date in the UI easier for the human eye to skim over.
Before:
After:
cc @AWare
> Sort the channel names and promo codes alphanumerically

- build.sbt
- frontend/src/templates/LandingPage.html
- project/build.properties
- Added a Description field to a newspaper landing page model, to render on the Newspaper landing page in subscriptions-frontend: https://github.com/guardian/subscriptions-frontend/pull/756
- Also updated to latest SBT and use same Scala version as membership-common.
cc @AWare @johnduffell
> Added a Description field to a newspaper landing page

- README.md
- nginx/promotions.conf
- nginx/setup.sh
What I've learned while getting memsubs-promotions running locally:
+ The certificate and key in the nginx config promotions.conf are now expired, but we can use the wildcard certificate and key from the identity platform config
+ Where to find the private dev config in S3
So, 
+ I've updated the nginx setup instructions to point to setting up nginx in identity-platform 
+ and so also now the nginx setup for this project can just add promotions.conf and start nginx
+ Updated cert and key in promotions.conf to point to the ones added by setting up identity-platform
+ Now the README points to where to download the config from S3
> Updated README and nginx config

- build.sbt
- cloudformation/memsub-promotions-cf.json
- conf/deploy.json
- conf/logback.xml
- conf/logger.conf
In [PR 103](https://github.com/guardian/memsub-promotions/pull/103), I accidentally made it so that when an artifact is generated in this app, it's in a folder called 'memsub-promotions' while riff-raff expects to find an artifact for an app 'promotions-tool'.
So let it be promotions-tool.
> Correct structure for generated artifact

- cloudformation/memsub-promotions-cf.yaml
Some cloudformation tweaks to use SSM and not use the github keys, and to limit the EC2 outbound connections to just the HTTPS port.
```
paul_brown [~] $ ./ssm ssh -p membership -t 'promotions-tool,membership,CODE'
The specified instance(s) are not eligible targets (AWS said InvalidInstanceId)
paul_brown [~] $ ./ssm ssh -p membership -t 'promotions-tool,membership,CODE'
========= i-08xxxxxxxxxxxxx4 =========
STDOUT:
ssh -i /private/var/folders/tc/64yqdxgx4jd7g7mvhlc62clj9hrltx/T/security_ssm-scala_temporary-rsa-private-key2558757191371071508.tmp xxxxxx@xxx.xxx.xxx.xxx;
```
cc @jacobwinch @davidfurey
> Some cloudformation tweaks to use SSM and not use the github keys

- cloudformation/memsub-promotions-cf.yaml
Removed the security group giving us SSH access to the box and instead attached the ingress rule to the instance's security group. This was because the default if no egress rule is selected is to open up a rule allowing outbound access to all ports and IP protocols to any location. See 'Remove Default Rule': https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
See the same change done on [Members Data API](https://github.com/guardian/members-data-api/pull/318).
cc @davidfurey @johnduffell
> Removed the security group giving us SSH access to the box, using instance group instead

- cloudformation/memsub-promotions-cf.yaml
Previously introducing an 'Allow' statement with a wide scope rendered an Allow statement with a more limited scope redundant, although this is not easy to spot when reviewing Cloudformation changes or applying changes (see https://github.com/guardian/memsub-promotions/pull/115).
This PR explicitly denies access to all S3 resources except for those defined in the ReadableS3Resources parameter, which means that inadvertently pulling in a statement with wide scope (e.g. by attaching a managed policy which allows access to all S3 resources) will no longer have these unintended consequences.
See also: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html#policy-eval-denyallow
> Tighten up S3 permissions

- build.sbt
- project/plugins.sbt
**1. logback-classic - logback-core** - SOLVED
Vulnerable module: ch.qos.logback:logback-classic [CVE-2017-5929] - Logback before 1.2.0 has a serialization vulnerability affecting the SocketServer and ServerSocketReceiver components
**2. xerces:xercesImpl** - UPDATE NOT POSSIBLE
Vulnerable module: xerces:xercesImpl [CVE-2017-10355] - **MODIFIED**
This vulnerability has been modified since it was last analyzed by the NVD. It is awaiting reanalysis which may result in further changes to the information provided.
**3. jackson-databind** - UPDATE NOT POSSIBLE
https://github.com/guardian/zuora-auto-cancel/pull/65
**4. io.netty:netty** - SOLVED
Vulnerable module: io.netty:netty [CVE-2015-2156] - Upgrade io.netty:netty to version 3.9.8.Final, 3.10.3.Final, 4.0.28.Final, 4.1.0.Beta5 or higher. …
> Upgrade libs - Snyk

- app/actions/GoogleAuthAction.scala
- app/controllers/AuthController.scala
- app/controllers/PromotionController.scala
- build.sbt
Similar to the work started here (https://github.com/guardian/memsub-promotions/pull/118/files), but with a slightly different motivation...
I want to use the latest membership-common so that I can make changes to the CatalogService.
There are no tests in this project, so I've manually tested GoogleAuth, creating a campaign, and creating a promo code.
> Update Guardian libraries in preparation for catalog loading changes

- app/actions/GoogleAuthAction.scala
As part of GDPR CyberEssentials we are encouraged to manage access to systems at a personal level via a documented process, rather than adding Google groups which are then in the control of other people.
cc @jacobwinch @davidfurey
> Only one managed group should have access to the tool

- build.sbt
https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-31507
We are pulling in old versions of jackson-databind via aws-sdks (the promo code tool needs to interact with dynamo). It's suggested here that overriding jackson-databind shouldn't be a breaking change. 
We are also pulling in an old version of jackson-databind to support Google auth.
I bumped the versions, signed in via my google account, and checked to see that some promo codes were coming through from the dynamo table.
Any other suggested checks?
// none. Inspired by Snyk.
Bumped jackson-databind and jackson-annotations to 2.9.7
> bump jackson-databind and jackson-annotations to 2.9.7

- build.sbt
This PR addresses a [snyk issue](https://app.snyk.io/org/the-guardian-cuu/project/d0c4fcd7-5943-49b1-878b-c7a8e9d64236/) as a result of depending on `com.gu.membership.common`. 
@johnduffell fixed the issue with membeship.common [with this PR](https://github.com/guardian/membership-common/pull/584) . Bumping version to use this 'fixed' version.
> bumps membership-common dependency

- cloudformation/memsub-promotions-lambdas-cf.yaml
The Lambda was prevented from deleting old backups due to this permision not being there. This might have also been causing the Lambda to execute three times.
Thanks for spotting that @pvighi!
> Fix Lambda Dynamo IAM permissions

- build.sbt
- nginx/promotions.conf
Here we go again. See description here: https://github.com/guardian/memsub-promotions/pull/130
Here's the Snyk issue:
https://app.snyk.io/org/the-guardian-cuu/project/d0c4fcd7-5943-49b1-878b-c7a8e9d64236/
Changes:
* update jackson-databind and jackson-annotations to 2.9.8
* Have also updated the certificate in the nginx config
I ran the app locally and just checked that there were promo codes coming through
> bump jackson-databind and jackson-annotations to 2.9.8

- app/controllers/PromotionController.scala
- frontend/src/services/PromotionService.es6
- frontend/src/templates/PromotionForm.html
In response to a production issue where promo codes linked to DEV/UAT product rate plan ids were added to the PROD Dynamo table 😱 
Full details are here: https://trello.com/c/OIpRqlVn/2219-investigate-misalignment-of-digital-pack-promo-code
The user (who is likely to be a developer anyway) will now see the following error message if there is a mismatch between the stage cookie and the product rate plan ids linked to the promo:
The logging also now contains an explanation of why the validation has been failed so we can work out what's going wrong.
> Prevent invalid product rate plan ids from being written to Dynamo

- build.sbt
Updating to latest membership-common to pick up the oneYear GW rate plans in the PromoCode tool introduced in v0.533 and https://github.com/guardian/membership-common/commit/cf8765205abee48f53604c50ad8828a8b3773f60
This fixes the issue where no prices and discounts show up against the rate plans, and makes the promotion uneditable.
Before in CODE:
After in CODE:
cc @rupertbates @arausuy @jorgeazevedo
> Updating to latest membership-common to pick up the oneYear GW palns

- cloudformation/memsub-promotions-cf.yaml
Disabling allocation of an external IP address as this box is now inside the private subnet.
Tested on CODE.
> Disabling allocation of external IP address as this box is now inside the private subnet

- build.sbt
- project/build.properties
The https://app.snyk.io/vuln/SNYK-JAVA-ORGAPACHEHTTPCOMPONENTS-31517
and https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-450917
are present in the promo tool.
Even though it's internal, it makes sense to keep things up to date.
I have also updated the SBT version to keep things sensible.
Depends on the PR I shipped yesterday: https://github.com/guardian/membership-common/pull/600
> snyk: update jackson version and apache commons httpclient

- build.sbt
- project/build.properties
- project/plugins.sbt
this updates jackson databind for the usual snyk issue.
also bumps scala/sbt versions, and also the sbt-dependency graph as that is needed for snyk monitor and the newer version is needed for latest sbt.
@alexflav23 @twrichards
> update jackson version for snyk

- frontend/src/templates/LandingPage.html
Add a note to the label of the landing page description field so that users are aware that they may use a subset of Github Markdown in the field
> Update the landing page description field label

- frontend/src/templates/PromotionForm.html
The promotion description field is now used in product page price cards as well as the checkout summary, so this PR updates the field description to reflect this:
> Update the promo description field label

- README.md
- nginx/BrewFile
- nginx/promotions.conf
- nginx/setup.sh
We are now using dev-nginx to handle SSL certs for local development rather than the Identity platform. This PR updates the promo tool to work the same way.
Based on https://github.com/guardian/subscriptions-frontend/pull/1267/files
> Use dev nginx

- build.sbt
- frontend/src/templates/LandingPage.html
- frontend/src/templates/PromotionForm.html
- frontend/src/templates/PromotionType.html
* Update sbt repo urls to use https - we were getting warnings that http is deprecated
* Hide the landing page image selector as we don't support setting images via promo codes at the moment
* Remove the landing page colour scheme selectors for DP and GW as we don't support those any more
* Change the descriptions of the various landing page fields to make it clear that the promo code description is used on the checkout only and then repurpose the roundel field for the product page price card text
> Landing page tweaks

- app/conf/WeeklyPlans.scala
- app/controllers/RatePlanController.scala
- build.sbt
- conf/application.conf
We have a new fixed term rate plan for Guardian Weekly, this PR makes the promo code tool aware of it.
I have also removed the old Guardian Weekly rate plans as we are no longer selling them and simplified the way the rate plans are displayed in the UI
> Add new three month fixed rate plan and remove old plans

- cloudformation/memsub-promotions-lambdas-cf.yaml
@markjamesbutler spotted that the schedule for the ETL Lambdas was created in the UI and not CFN, hence this change.
> Define schedule for ETL to SF and Data Lake in CFN

- frontend/src/templates/PromotionForm.html
Update the label for the 'description' field to reflect the fact that it is now used on the showcase page as well as the checkout.
> Update label for the 'description' field

- app/controllers/RatePlanController.scala
- frontend/scss/main.scss
- frontend/src/controllers/RatePlanListController.es6
- frontend/src/templates/PromotionForm.html
- frontend/src/templates/RatePlanList.html
- test/ratePlans/RatePlanControllerSpec.scala
Currently the promotion form only shows pricing information for GBP prices which makes it very hard to work out the correct discount amounts for other currencies. 
This PR adds in pricing in all other currencies which we support.
> Multi currency discounts

- build.sbt
- frontend/src/templates/LandingPage.html
This PR adds the new fields to the promo tool so that paper can have copy editing in more places on the landing page
https://trello.com/c/rdC88F6V/3593-add-fields-to-promo-code-tool-to-enable-print-landing-page-input
old
https://memsub-promotions.gutools.co.uk/#/promotion/39ddaac7-5a5e-4b77-b004-2a60749ebdce
new
and the result (example copy)
> add fields to newspaper landing page section in the promo tool

- build.sbt
Bintray is going away on 1st may, we don't actually use it here, but there was a reference hanging around that I removed.
> remove unused bintray reference

- frontend/src/templates/LandingPage.html
#189 removed the radio buttons which set the default product for a newspaper promotion. This made sense because they are not used by support-frontend currently however it broke deserialisation of new promotions in the `PromotionController` class because the `NewsPaperLandingPage` case class defined in membership-common expects a value for `defaultProduct`
This PR adds those fields back in.
[**Trello Card**](https://trello.com/c/f05ZuVWs/3676-fix-newspaper-promotion-creation-in-promo-code-tool)
> Add default product radio buttons back into the newspaper form

- .github/workflows/snyk.yml
The currently recommended way of integrating [Snyk](https://app.snyk.io/org/the-guardian-cuu/) with a repository is to use Github actions as described in [this doc](https://github.com/guardian/security-hq/blob/main/hq/markdown/snyk.md#integrating-snyk-with-your-projects)
This PR adds an action to handle Snyk integration. I have also disabled the TeamCity build step which was previously managing the integration.
> Add a Github action for Snyk integration

- .github/workflows/snyk.yml
This PR makes snyk focus on the root build.sbt file, rather than going through the whole repo and making loads of "projects"
It also makes it run on a merge to main, rather than waiting until the next day.  This should use less resources and also get the results in the dashbord quicker.
> stop snyk finding lots of random files to scan

- build.sbt
vulnerability: https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2421244
setting `jackson-module-scala` as well solves a compatibility issue with Play
Tested in CODE
> jackson-databind 2.13.3

- build.sbt
it's getting an old version of okhttp via membership-common, which has a vulnerability.
See https://github.com/guardian/membership-common/pull/740
> bump membership-common

- conf/riff-raff.yaml
- project/plugins.sbt
Ubuntu Bionic is approaching end of life. This PR updates the metering api to use an AMI based on Jammy.
> Ubuntu Jammy

- cloudformation/memsub-promotions-cf.yaml
- conf/logger.conf
- conf/riff-raff.yaml
- project/plugins.sbt
With this PR the cloudwatch log group has been renamed from:
`MemsubPromotions-<STAGE>`
to
`membership-promotions-tool-<STAGE>`
This is because it now uses the standard `configure-logs` script
> Ubuntu Jammy (v2)

- cloudformation/memsub-promotions-lambdas-cf.yaml
- lambdas/src/MembershipSub-PromoCode-View-Dynamo-to-Salesforce.js
Previously we were getting salesforce credentials from environment variables, and this recently got wiped.
This PR changes it to fetch the config from S3. In a follow up we'll migrate to Secrets Manager, as this is now the standard place for salesforce config.
This PR also removes the use of KMS, which was for decrypting the environment variables.
> salesforce lambda: load config from S3

- .github/workflows/memsub-promotions-lambdas.yml
Currently updating the Cloudformation stack has to happen manually. It'd be better for Riff Raff to deploy it.
Note: I've removed CODE from allowed stages in the RR config, since it currently fails to deploy the lambdas and there isn't a CODE Cloudformation stack.
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technolo …
> Configure Riff Raff to deploy lambda cloudformation

- frontend/src/config/DateConfig.es6
- frontend/src/main.es6
After the Node + NPM lib upgrades in #255 we found that the date picker was sometimes breaking. After lots of debugging/trial and error we discovered that the datepicker was only broken when the day potion of the date was > 12. This lead us to believe this was a date locale problem. ~~As an experiment we tried removing the formatDate change we were making in DateConfig and this got things working. We aren't sure why! It doesn't seem to have broken anything else.~~ Out first approach _did_ break something. Dates in the input field weren't correctly formatted. Instead the right approach is to add the formatting back in and to add a parseDate function, which knows how to go from our formatted date back to a Date object.
Open a date picker!
-   [ ] [Tested with screen …
> Fix (sometimes) broken date picker

- frontend/src/templates/AvailableCountries.html
Fixes an alignment issue with the country checkboxes, reported by Craig.
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> Fix country checkbox alignment

- app/com/gu/memsub/subsv2/Plan.scala
- app/com/gu/memsub/subsv2/reads/ChargeListReads.scala
The `readSupporterPlusV2ChargeList` ChargeListReads object was quite loose in the type of charges it would match which meant that some subscriptions could be mistakenly identified as supporter plus subs.
This PR tightens the deserialisation up so that it only matches charges with billing periods which are valid for supporter plus subscriptions.
original change in https://github.com/guardian/members-data-api/pull/1033
> Better validation for readSupporterPlusV2ChargeList

- cloudformation/memsub-promotions-lambdas-cf.yaml
- lambdas/package.json
- lambdas/src/MembershipSub-PromoCode-View-Dynamo-to-Salesforce.js
- lambdas/yarn.lock
We decided to use S3 temporarily to get this lambda working quickly.
But the stream uses Secrets Manager for salesforce credentials.
Tested with the CODE version of this lambda:
TODO later - delete config files from S3
> Use secrets manager for salesforce credentials

- app/com/gu/config/SupporterPlusRatePlanIds.scala
- app/com/gu/memsub/promo/Formatters.scala
- app/com/gu/memsub/promo/Promotion.scala
- app/controllers/RatePlanController.scala
- app/wiring/AppComponents.scala
- frontend/src/templates/EnvironmentMenu.html
We want to be able to create discounts for the supporter plus product, this PR adds in the necessary rate plans and makes supporter plus available as a product from the burger menu.
> Add supporter plus

- conf/touchpoint.PROD.conf
The supporter plus product rate plan ids in config were for the old V1 rate plans, this PR updates them to the V2 versions
> Add the correct product rate plan ids for supporter plus

- app/com/gu/memsub/subsv2/services/CatalogService.scala
A [previous PR](https://github.com/guardian/memsub-promotions/pull/276) bumped the AWS dependencies.
We're now getting errors talking to S3 in the logs:
`Failed to load JSON due to com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. If you start to see this issue after you upgrade the SDK to 1.12.460 or later, it could be because the bucket provided contains '/'.`
My testing in CODE didn't trigger this error, I think because the example promo I used didn't require this data.
The S3 SDK has changed and the parameters to `GetObjectRequest` now need to be different.
> Fix S3 call

- conf/touchpoint.CODE.conf
Updates the rate plan IDs to match [this](https://github.com/guardian/support-frontend/blob/main/support-models/src/main/scala/com/gu/support/catalog/Product.scala#L64-L67) (and Zuora).
As per https://github.com/guardian/memsub-promotions/pull/275
> Update Supporter+ rate plan IDs

- app/com/gu/memsub/subsv2/Plan.scala
- app/com/gu/memsub/subsv2/services/CatalogService.scala
Follow up from https://github.com/guardian/memsub-promotions/pull/278
Uses the V2 Supporter Plus plans from Zuora.
This is now working locally.
Thanks 🙇 be to @johnduffell for helping me work out how the parsing of the Zuora catalogue works here.
> fix: use SupporterPlusV2 Zuora catalogue plans

- app/com/gu/memsub/subsv2/Plan.scala
- app/com/gu/memsub/subsv2/services/CatalogService.scala
Reverts guardian/memsub-promotions#279
I completely forgot - this worked on `PROD`. Now it doesn't. 
The `FrontendId` in Zuora for `PROD` is `Yearly | Monthly`. In `CODE` it's `YearlyV2 | MonthlyV2`.
My suggestion is that we revert this change, and change `CODE` Zuora source data to reflect `PROD`.
An alternative would be to change the `FrontendId` in `PROD` to the `V2` version, but I am unsure of the downstream knockon effects.
> Revert "fix: use SupporterPlusV2 Zuora catalogue plans"

- nginx/promotions.conf
Uses `TLSv1.2` and `TLSv1.3` for local development. We were getting a `ERR_SSL_VERSION_OR_CIPHER_MISMATCH` error locally and this fixes that.
We have seen strange behaviour where this config was affecting the `support.gulocal.com`'s config. We will need to dig deeper into that.
> Use modern TLS protocols and ciphers

- app/com/gu/memsub/auth/common/MemSub.scala
- app/com/gu/memsub/images/ResponsiveImage.scala
- build.sbt
- project/build.properties
- project/plugins.sbt
We are now getting snyk warnings for Play 2's Akka dependency.
Play 3 [replaces Akka with Pekko](https://www.playframework.com/documentation/3.0.x/Migration30#Migration-from-Akka-to-Pekko), which resolves this.
Tested in CODE
> Upgrade to Play 3

- frontend/package.json
- frontend/yarn.lock
Reverts guardian/memsub-promotions#305
Reverting this because it breaks webpack dev server locally
> Revert "Bump webpack-dev-server from 4.15.1 to 5.0.4 in /frontend"

- frontend/package.json
- frontend/yarn.lock
Upgrading angular-ui-router causes an error when clicking on the new campaign button:
The error is 
```
stateService.js:35 Error: Transition Rejection($id: 1 type: 4, message: This transition is invalid, detail: The following parameter values are not valid for state 'editCampaign': [code:undefined])
at invalidTransitionHook (invalidTransition.js:10:1)
at invokeCallback (transitionHook.js:90:44)
at TransitionHook.invokeHook (transitionHook.js:95:1)
at TransitionHook.invokeHooks (transitionHook.js:63:1)
at Transition.run (transition.js:600:23)
at StateService.transitionTo (stateService.js:369:1)
at StateService.go (stateService.js:265:1)
at stateDirectives.js:55:1
at angular.js:21765:1
at TaskTracker.completeTask (angular.js:21403:1)
```
Reverting this upgrade for now to unblock business …
> Revert upgrade to angular-ui-router

- .gitignore
- app/com/gu/aws/AwsS3Client.scala
- app/com/gu/config/SupporterPlusRatePlanIds.scala
- app/com/gu/memsub/subsv2/Plan.scala
- app/com/gu/memsub/subsv2/services/CatalogService.scala
- app/controllers/RatePlanController.scala
- conf/touchpoint.CODE.conf
- conf/touchpoint.PROD.conf
This adds the 4 new 3-tier product rate plans to the Promo Tool.
Updated list of product rate plans for Supporter Plus:
- Annual
- Monthly
- Guardian Weekly Rest Of World Monthly (NEW)
- Guardian Weekly Rest Of World Annual (NEW)
- Guardian Weekly Domestic Annual (NEW)
- Guardian Weekly Domestic Monthly (NEW)
- Access the Promo Tool in CODE [here](https://promo.code.memsub-promotions.gutools.co.uk)
- Select from the top left dropdown "Supporter Plus"
- Create new promotion
- See the new product rate plans available
- Example of promotion with new product rate plan on CODE [here](https://promo.thegulocal.com/#!/promotion/9c3594cb-139c-4c02-9e29-ae41e201590f)
The reader revenue team are able to create promotion codes with the new 3-tier product rate plans.
> feat: add 3-tier product rate plans to promotions tool

- app/com/gu/config/SubsV2ProductIds.scala
- app/com/gu/config/SupporterPlusRatePlanIds.scala
- app/com/gu/config/TierThreeRatePlanIds.scala
- app/com/gu/memsub/ProductFamily.scala
- app/com/gu/memsub/promo/Formatters.scala
- app/com/gu/memsub/promo/Promotion.scala
- app/com/gu/memsub/subsv2/Plan.scala
- app/com/gu/memsub/subsv2/reads/CatPlanReads.scala
- app/com/gu/memsub/subsv2/reads/ChargeListReads.scala
- app/com/gu/memsub/subsv2/services/CatalogService.scala
- app/controllers/RatePlanController.scala
- app/wiring/AppComponents.scala
- conf/touchpoint.CODE.conf
- conf/touchpoint.PROD.conf
- frontend/src/templates/EnvironmentMenu.html
This PR
- Introduces the new `TierThree` product
- Removes the now obsolete `ratePlans` from `SupporterPlus` that were going to fulfil this functionality
It's a relatively large PR, but I think that's just the nature of adding things to the promo tool.
> Add TierThree product and remove SupporterPlus ratePLans

- conf/touchpoint.PROD.conf
These `ratePlans` are no longer used and we should be using the `tierThree` product instead
> fix: remove tier three rateplans from supporterplus

- build.sbt
Snyk has flagged the current version of jackson-core as a high vulnerability - https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-7569538
This comes via Play:
Although there are newer versions of jackson without that vulnerability, the latest version of Play still uses the old version of jackson. (There is [a PR](https://github.com/playframework/playframework/pull/12440) but things move slowly.)
So for now we have to override the jackson-core version, until Play is updated.
Tested in CODE
> Override jackson-core

- conf/touchpoint.CODE.conf
- conf/touchpoint.PROD.conf
[Trello](https://trello.com/c/h7MX4D5w/260-remove-all-references-to-hard-coded-invoice-template-ids-and-move-all-customers-to-new-invoice-template)
This removes all references to hard-coded invoice template IDs.
We have recently created a [generic HTML template](https://github.com/guardian/zuora-config/blob/main/finance/invoice-templates/system-default.html) that will be used by default for all products / accounts.
> feat: remove hard-coded invoice template IDs

- build.sbt
htmlunit has been flagged by dependabot.
It comes via scalatest, which has not migrated to a safe version
> Exclude htmlunit
